language: objective-c
osx_image: xcode10.2
xcode_workspace: Psorcast.xcworkspace
xcode_scheme: Psorcast
cache:
- bundler
before_install:
- echo -e "machine github.com\n  login $CI_USER_TOKEN" >> ~/.netrc
install:
- gem install bundler
- bundle install
script:
- travis_wait 60 ./travis/build.sh
branches:
  only:
  - master
  - "/^stable-.*$/"
